[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib", "../third_party"]
via_ir = true
optimizer = true
optimizer_runs = 200

# Remappings for common dependencies
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@protobuf3-solidity-lib/=node_modules/@lazyledger/protobuf3-solidity-lib/contracts/",
    "@forge-std/=../third_party/forge-std/src/",
]

# Gas optimization
[profile.default.optimizer_details.yulDetails]
optimizerSteps = "dhfoDgvulfnTUtnIf[xa[r]EscLMcCTUtTOntnfDIulLculVcul [j]Tpeulxa[rul]xa[r]cL gvif CTUca[r]LSsTFOtfDnca[r]Iulc] jmul[jul] VcTOcul jmul"

# Test configuration
[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[profile.ci.fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options