site_name: PostFiat SDK Documentation
site_description: Proto-first multi-language SDK with Python and TypeScript support
site_url: https://allendy.github.io/pfsdk
repo_url: https://github.com/allendy/pfsdk
repo_name: allendy/pfsdk

extra:
  version: 0.1.0-dev
  release_tag: v0.1.0-dev
  release_url: ""
  release_date: ""

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - swagger-ui-tag

nav:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - Development: DEVELOPMENT.md
  - Contributing: CONTRIBUTING.md
  - API Reference:
    - OpenAPI Specification: api/openapi.md
    - Python SDK: generated/python/index.html
    - Protocol Buffers: generated/proto/index.md
  - Research:
    - Key Management: research/KEY-MANAGEMENT.md
    - A2A Selective Disclosure: research/A2A-SELECTIVE-DISCLOSURE-EXTENSION.md
    - XRPL Chat Application: research/XRPL-CHAT-APPLICATION-ADAPTATION.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true