site_name: PostFiat SDK Documentation

plugins:
  - search
  - swagger-ui-tag
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            merge_init_into_class: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - Development: DEVELOPMENT.md
  - Contributing: CONTRIBUTING.md
  - API Reference:
      - OpenAPI Specification: api/openapi.md
      - Python SDK: python-api.md
      - Protocol Buffers: generated/proto/index.md
  - Research:
      - Key Management: research/KEY-MANAGEMENT.md
      - A2A Selective Disclosure: research/A2A-SELECTIVE-DISCLOSURE-EXTENSION.md
      - XRPL Chat Application: research/XRPL-CHAT-APPLICATION-ADAPTATION.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true