name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: write  # Required for auto-committing generated files

env:
  PYTHON_VERSION: "3.12"

jobs:
  proto-validation:
    name: Proto Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Lint proto files
        run: |
          cd proto
          buf lint
      
      - name: Check for breaking changes
        if: github.event_name == 'pull_request'
        run: |
          cd proto
          # Skip breaking change detection if main branch doesn't exist or can't be accessed
          if git ls-remote --exit-code --heads origin main > /dev/null 2>&1; then
            buf breaking --against 'https://github.com/${{ github.repository }}.git#branch=main,subdir=proto' || echo "⚠️ Breaking change detection failed, skipping"
          else
            echo "ℹ️ Main branch not found, skipping breaking change detection"
          fi

  code-generation:
    name: Code Generation
    runs-on: ubuntu-latest
    needs: proto-validation
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml protobuf grpcio-tools
      
      - name: Generate protobuf code
        run: |
          cd proto
          buf mod update
          buf generate --template buf.gen.yaml
      
      - name: Verify generated code
        run: |
          python -c "
          import sys
          sys.path.insert(0, '.')
          from postfiat.v3 import messages_pb2
          print('✅ Generated code imports successfully')
          "

      - name: Generate Python types from protobuf
        run: python scripts/generate_python_types.py

      - name: Generate protobuf tests
        run: python scripts/generate_protobuf_tests.py

      - name: Run tests
        run: |
          # Run both manual and generated tests
          python -m pytest tests/ -v --tb=short

      - name: Generate and run protobuf tests
        run: |
          python scripts/generate_protobuf_tests.py
          python -m pytest tests/generated/ -v --tb=short

      - name: Commit generated files to main branch
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f postfiat/types/enums.py postfiat/exceptions.py postfiat/v3/*_pb2.py postfiat/v3/*_pb2_grpc.py
          if ! git diff --staged --quiet; then
            git commit -m "chore: add generated files for main branch [skip ci]"
            git push origin main
          else
            echo "No changes to commit"
          fi

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: code-generation
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      
      - name: Generate protobuf code
        run: |
          cd proto
          buf mod update
          buf generate --template buf.gen.yaml
      
      - name: Test package installation
        run: |
          python -c "import postfiat; print(f'PostFiat SDK v{postfiat.__version__} installed successfully')"

      - name: Generate protobuf tests
        run: python scripts/generate_protobuf_tests.py

      - name: Run test suite
        run: |
          # Run both manual and generated tests
          python -m pytest tests/ -v --tb=short

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: [proto-validation, tests]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine pyyaml
      
      - name: Generate protobuf code
        run: |
          cd proto
          buf mod update
          buf generate --template buf.gen.yaml
      
      - name: Build package
        run: python -m build
      
      - name: Check package
        run: twine check dist/*
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
