name: Test Manual Trigger

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        default: 'hello'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: |
          echo "Manual trigger is working!"
          echo "Input value: ${{ github.event.inputs.test_input }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}" 